name: snowflake_dart
description: A simple snowflake id generator for dart.
version: 1.1.0
repository: https://github.com/JYeop/snowflake_dart
issue_tracker: https://github.com/JYeop/snowflake_dart/issues
homepage: https://github.com/JYeop/snowflake_dart
documentation: https://github.com/JYeop/snowflake_dart

# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.12.0 <4.0.0'


# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
